### ISSUE TITLE
venv and pycache is not gitignore

### ISSUE THREAD

**Issue by functionstackx** [LemonFace0309/Deluxe-Consignment#1]
It is important to gitignore venv and pycache as it is not useful to track as it is binary code that will not be edited by developers

https://stackoverflow.com/questions/3719243/best-practices-for-adding-gitignore-file-for-python-projects
https://stackoverflow.com/questions/42306410/gitignore-syntax-how-to-exclude-virtualenv-sub-directories
https://intellipaat.com/community/19263/git-continues-to-control-changes-on-pycache-even-when-it-is-in-gitignore

**Comment by jimmyygit** [comment]
Thanks Oren!
I've been wanting to add pycache to .gitignore for a while but couldn't find much success -.-
Also, what if we wanted to share a venv? Should we not share it over git?

**Comment by functionstackx** [comment]
Venv should not be shared due to developer dependent configs. your requirements.txt already specifics which packages you are using, The only thing not specified is your python version, which can easily be communicated over README.md

example of developer dependent configs in venv
"home = C:\Users\charl\AppData\Local\Programs\Python\Python38-32" 
https://github.com/LemonFace0309/Deluxe-Consignment/blob/master/venv/pyvenv.cfg

Python Version Manager
https://github.com/pyenv/pyenv

Solution to adding pycache to existing committed git repo. I had to google this one too, as this is not a very common issue.
https://stackoverflow.com/questions/6380196/gitignore-does-not-work

Here are a couple links to best practices for github repos.
https://libzx.so/main/learning/2016/03/13/best-practice-for-virtualenv-and-git-repos.html
https://github.com/codica2/pull-request-best-practices

Message me on facebook for further suggestions. I would recommend looking into Jira, aglie process, pull requests, and issues.

**Comment by functionstackx** [comment]
After looking into further, I do not see a requirements.txt. It specifics which packages and package versions are required for this project.

https://pip.pypa.io/en/stable/user_guide/
https://note.nkmk.me/en/python-pip-install-requirements/
